
[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true

[project]
name = "finance_app"
version = "0.1.0"
description = "Aplicativo de FinanÃ§as Pessoais"
requires-python = ">=3.12"
